[SA-15302] Parse Cookie header and its attrs. Use the sessionid as mark for upstream socket
appgate-sdp-int/nginx pull request #3
Opened 2020-10-30 12:38 UTC by kosmas-valianos

2020-10-30 12:43 UTC, kosmas-valianos commented
Needs some systemd changes in stratus-appliance in order for worker processes to have permissions to `setsockpt()`. For simplicity the tests were run with `master_process off;` i.e. without worker processes => root process

2020-11-02 11:38 UTC, thomascellerier requested changes

2020-11-02 11:38 UTC, thomascellerier commented on src/http/modules/ngx_http_proxy_module.c
> +    r->upstream->peer.so_mark = 0x127f;
Looks like the firewall mark is still hardcoded.

2020-11-02 13:25 UTC, thomascellerier approved these changes

2020-11-02 14:52 UTC, kosmas-valianos commented on src/http/modules/ngx_http_proxy_module.c
> +    r->upstream->peer.so_mark = 0x127f;
Ooops leftover

2020-11-02 14:52 UTC, merged